name: CI

on:
  push:
    branches: ['master']
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.5.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
      
      - uses: UnlyEd/github-action-deploy-on-vercel@latest
        with:
          command: "npx vercel .vercel_build_output --confirm --debug --token ${{ secrets.VERCEL_TOKEN }}"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      # - run: "echo \"Found deployment url: ${{ env.VERCEL_DEPLOYMENT_URL }}\""
      # - uses: amondnet/vercel-action@v20 #deploy
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
      #     github-token: ${{ secrets.GH_PAT }} #Optional
      #     vercel-args: '--prod' #Optional
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required


